<?
echo $help;
?>

<h2>Login</h2>

<?php echo $this->tag->form(["login/login",'class' =>'form']); ?>


<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField(["email",'class' => 'form-control col-6']); ?>
</p>

<p>
    <label for="email">Password</label>
    <?php echo $this->tag->textField(["password",'class' => 'form-control col-6']); ?>
</p>
<p>
    <label for="email">Not a User ?</label>
    <?php echo $this->tag->linkTo("signup","Sign Up"); ?>
</p>

<p>
    <?php echo $this->tag->submitButton(["login",'class' => 'btn btn-primary']); ?>
</p>

</form>

<?php

// print_r($data);
?>


