<?php
// $user_id = $_GET['user_id'];
print_r($currentUser[0]->username);


?>

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Blog Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/blog/">



    <!-- Bootstrap core CSS -->
    <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
</head>

<body class="container-fluid>
    
<div class=" container">
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <a class="link-secondary" href="http://localhost:8080/friend?user_id=<?php echo $currentUser[0]->user_id?>">Add Friend</a>
            </div>
            <div class="col-4 text-center h2">
                CEDBOOK
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="link-secondary" href="#" aria-label="Search">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24">
                        <title>Search</title>
                        <circle cx="10.5" cy="10.5" r="7.5" />
                        <path d="M21 21l-5.2-5.2" />
                    </svg>
                </a>
                <?php echo $this->tag->linkTo(["login/signout", "Sign Out", 'class' => 'btn btn-secondary p-5']); ?>
            </div>
        </div>
    </header>



    <main class="container">
        <div class="row mb-5">
            <div class="col-12">
                <div class="h2">Write New Post </div>
            </div>
            <div class="col-12 border">
                <br>
                <?php echo $this->tag->form(["index/newpost", 'class' => 'form justify-content ']); ?>

                <?php echo $this->tag->hiddenField(["post_user_id", "value" => $currentUser[0]->user_id,]); ?>
                <p>
                    <label for="title">Title</label>
                    <?php echo $this->tag->textField(["title", 'class' => 'form-control']); ?>
                </p>
                <p>
                    <label for="description">Description</label>
                    <?php echo $this->tag->textArea(["description", 'class' => 'form-control']); ?>
                </p>
                <p>
                    <label for="description" class="form-label">File</label>
                    <?php echo $this->tag->fileField(["file_path", 'class' => 'form-control']); ?>
                </p>

                <p>
                    <?php echo $this->tag->submitButton(["Post", 'class' => 'btn btn-primary']); ?>
                </p>
                <?php echo $this->tag->endform(); ?>
            </div>
        </div>

        <div class="row g-5">
            <div class="col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border-bottom">
                    Feeds
                </h3>
                <?php foreach ($posts as $post) { ?>
                    <article class="blog-post mb-5">
                        <div class="card">
                            <img src="..." class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title"><?php echo  $post->title; ?></h5>
                                <p class="card-text"><?php echo  $post->description; ?></p>

                                <a href="http://localhost:8080/index/like?post_id=<?php echo $post->post_id; ?>&user_id=<?php echo $currentUser[0]->user_id ?>" class="btn btn-primary">Like
                                    <span class="badge badge-danger "><?php echo $post->likes ?></span>
                                </a>
                                <button type="button" class="btn btn-secondary " data-bs-toggle="collapse" data-bs-target="#demo<?php echo $post->post_id ?>">Comments
                                   
                                </button>


                                <div id="demo<?php echo $post->post_id ?>" class="collapse mt-3">
                                    <?php echo $this->tag->form(["index/comment", 'class' => 'form justify-content ']); ?>
                                    <?php echo $this->tag->hiddenField(["user_id", "value" => $currentUser[0]->user_id,]); ?>
                                    <?php echo $this->tag->hiddenField(["username", "value" => $currentUser[0]->username,]); ?>
                                    <?php echo $this->tag->hiddenField(["post_user_id", "value" => $post->post_id,]); ?>
                                    <?php echo $this->tag->textField(["comment", 'class' => 'form-control']); ?>
                                    <?php echo $this->tag->submitButton(["Reply", 'class' => 'btn btn-primary mt-2 mb-2 float-end me-2']); ?>
                                    <?php foreach ($comments as $comment) {
                                        
                                        if ($comment->comment_post_id == $post->post_id) {
                                            
                                            echo "<div class='row container'>
                                            <div class='col-2 ms-4 mt-2 pt-2 pb-2 me-1'>
                                                 <svg xmlns='http://www.w3.org/2000/svg' width='50' height='50' fill='currentColor' class='bi bi-person-circle' viewBox='0 0 16 16'>
                                                <path d='M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z'/>
                                                <path fill-rule='evenodd' d='M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z'/>
                                                </svg>
                                               
                                            </div>
                                            <div class='col-9 mt-3 me-2'>
                                            <div class='row h4 text-secondary'>
                                            $comment->username 
                                            </div>
                                            <div class='row'>
                                            $comment->comment
                                            </div>
                                           
                                            </div>
                                            
                                            </div>
                                            <br>";
                                        }
                                    }
                                    ?>

                                    <?php echo $this->tag->endform(); ?>
                                </div>

                            </div>
                        </div>
                    </article>
                <?php } ?>
            </div>

            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                        <h4 class="fst-italic">About</h4>
                        <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>
                    </div>
                </div>
            </div>
        </div>

    </main>

    <footer class="blog-footer">
        <p>
            <a href="#">Back to top</a>
        </p>
    </footer>



</body>

</html>