<?php
// print_r($users);
$friends = json_decode($currentUser[0]->friends);
print_r(json_encode($_SESSION['friends']));
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Document</title>
</head>

<body>
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <a class="link-secondary" href="http://localhost:8080/friend/">Add Friend</a>
            </div>
            <div class="col-4 text-center h2">
                CEDBOOK
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="link-secondary" href="#" aria-label="Search">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24">
                        <title>Search</title>
                        <circle cx="10.5" cy="10.5" r="7.5" />
                        <path d="M21 21l-5.2-5.2" />
                    </svg>
                </a>
                <?php echo $this->tag->linkTo(["login/signout", "Sign Out", 'class' => 'btn btn-secondary']); ?>
            </div>
        </div>
    </header>

    <main class="container mt-4">
        <?php foreach ($users as $user) {
            // print_r($user->user_id);
            if ($user->user_id == $currentUser[0]->user_id) {
                continue;
            } ?>

            <div class="row border p-3 mb-5">
                <div class="col-2 border-right ">
                    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                    </svg>
                </div>
                <div class="col-6 ps-5 ">
                    <div class="row h4 "><?php echo $user->username; ?></div>
                    <div class="row small text-primary"><?php echo $user->name; ?></div>
                    <div class="row"><?php echo $user->email; ?></div>
                    <div class="row small text-success"><?php echo $user->city; ?></div>
                </div>
                <div class="col-2"></div>
            <?php
            $flag = 0;
            if (isset($friends)) {
                foreach ($friends as $key => $friend) {


                    if ($key == $user->user_id) {

                        echo " <div class='col-2 border-left ps-5 btn unfollow' data-user_id='" . $user->user_id . "' data-currentuser_id='" . $currentUser[0]->user_id . "'>
                        <svg xmlns='http://www.w3.org/2000/svg' width='30' height='30' fill='currentColor' class='bi bi-person-check mb-3' viewBox='0 0 16 16'>
                        <path d='M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z'/>
                        <path fill-rule='evenodd' d='M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z'/>
                        </svg>                   
                        <br>
                        <div class='text-danger'>Unfollow</div>
                    </div>";
                        $flag = 1;
                        break;
                    }
                }
                if ($flag != 1) {

                    echo " <div class='col-2 border-left ps-5 btn follow' data-user_id='" . $user->user_id . "' data-currentuser_id='" . $currentUser[0]->user_id . "'>
                    <svg xmlns='http://www.w3.org/2000/svg' width='30' height='30' fill='currentColor' class='bi bi-person-plus mb-3' viewBox='0 0 16 16'>
                        <path d='M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z' />
                        <path fill-rule='evenodd' d='M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z' />
                    </svg>
                    <br>
                    <div class='text-primary'>Follow</div>
                </div> 
                ";
                }
            } else {
                echo " <div class='col-2 border-left ps-5 btn follow' data-user_id='" . $user->user_id . "' data-currentuser_id='" . $currentUser[0]->user_id . "'>
                <svg xmlns='http://www.w3.org/2000/svg' width='30' height='30' fill='currentColor' class='bi bi-person-plus mb-3' viewBox='0 0 16 16'>
                    <path d='M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z' />
                    <path fill-rule='evenodd' d='M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z' />
                </svg>
                <br>
                <div class='text-primary'>Follow</div>
            </div> 
           
            ";
            }
            echo " </div>";
        } ?>

    </main>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="../../../public/js/friend.js"></script>

</html>